name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.1
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Upload bin
      uses: actions/upload-artifact@v2
      with:
        name: rusty-ocean
        path: target/release/rusty-ocean
